version: '3'
services:
  graphite:
    image: grafana/grafana
    container_name: grafana
    ports:
      - '3000:3000'
    volumes:
      - ./data:/var/lib/grafana
      - ./log:/var/log/grafana
      - ./provisioning:/etc/grafana/provisioning
    env_file:
        - ./conf/config.monitoring
